# Generated by Django 5.1.1 on 2024-09-26 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="customer_information",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=64)),
                ("password", models.CharField(max_length=128)),
                ("firstName", models.CharField(max_length=64)),
                ("lastName", models.CharField(max_length=64)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        max_length=1,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="dog_information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("age", models.PositiveIntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dogs",
                        to="doggyDayCareCustomerInterface.customer_information",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Dog Information",
            },
        ),
        migrations.CreateModel(
            name="AppointmentInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("purpose", models.CharField(max_length=255)),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doggyDayCareCustomerInterface.dog_information",
                    ),
                ),
            ],
        ),
    ]
