# Generated by Django 5.1.1 on 2024-09-15 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="customer_information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.IntegerField()),
                ("username", models.CharField(max_length=64)),
                ("password", models.CharField(max_length=20)),
                ("firstName", models.CharField(max_length=64)),
                ("lastName", models.CharField(max_length=64)),
                ("gender", models.CharField(max_length=1)),
                ("address", models.CharField(max_length=64)),
                ("state", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="dog_information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dog_name1", models.CharField(max_length=64)),
                ("dog_name2", models.CharField(max_length=64)),
                ("dog_age1", models.IntegerField()),
                ("dog_age2", models.IntegerField()),
                (
                    "dog_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doggyDayCareCustomerInterface.customer_information",
                    ),
                ),
            ],
        ),
    ]
