# Generated by Django 5.1.1 on 2024-09-26 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doggyDayCareCustomerInterface", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AppointmentInformation",
            new_name="appointment_information",
        ),
    ]
